version: '3.1'

services:

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    ports:
      - 8080:80
    restart: always
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: